### ISSUE TITLE
You've done a wonderful job, just one suggestion...

### ISSUE THREAD

**Issue by SkyLeach** [fannheyward/coc-marketplace#172]
# Add (or document) mappings

If you have mappings for this, I was unable to find them even in the code.  The
ability to both view details of and uninstall or deactivate extensions from the
marketplace plugin would make it far more useful.  Right now, the only thing I
know how to do with this plugin is install extensions.  Every action I take
after that, just installs them again.

I see where the [actions have been added](https://github.com/fannheyward/coc-marketplace/blob/1300f80625ef750a3d6aece90db3cce919d8802a/src/marketplace.ts#L21-L39)
but no mappings.

I could spend more time at this point figuring out exactly how to map the
actions through CocList but I just don't much time at all and you probably
already know how.

note: I use marketplace through CocList like so:
```vim
nnoremap <silent><nowait> <space>m  :<C-u>CocList marketplace<cr>
```

**Comment by fannheyward** [comment]
coc-marketplace didn't provide any mappings, you can custom set mappings if you need.

**Comment by SkyLeach** [comment]
Could you at least document how?  I haven't managed to figure out how to map through CocLists

**Comment by fannheyward** [comment]
There is no _standard_ way to do mapping, you can set it as your like, for example in normal mode or with leader key.

**Comment by SkyLeach** [comment]
I don't care about standard, I want to know *any* way of using it other than to install.  The README.md is missleading since pressing return on an already installed item just installs it again.  That's not what one expects.

Right now I can't use it for anything but browsing and installing.  I have to manually type CocUninstall <package> to remove and I have no idea how to get additional information.
