### ISSUE TITLE
SSL version error when executing ":CocList marketplace"

### ISSUE THREAD

**Issue by perfectspr** [fannheyward/coc-marketplace#37]
[coc.nvim] Error on "CocList marketplace": write EPROTO 4548101568:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

I'm using a proxy.

**Comment by fannheyward** [comment]
This is caused by http_proxy, latest coc.nvim has fixed this error.
