### ISSUE TITLE
请问可以支持 Node 8 吗 ？

### ISSUE THREAD

**Issue by IndexXuan** [fannheyward/coc-marketplace#4]
使用了下，报错了，用了 .finally 语句，请考虑支持下 Node 8，tsconfig.json 编译目标降低下 ~

**Comment by IndexXuan** [comment]
不好意思，同时又报了 exts 不可迭代，是网络问题，没请求到 extensions 列表吗 ？

**Comment by fannheyward** [comment]
收到，我搭一个 8 的环境测试一下。

**Comment by fannheyward** [comment]
0.1.1 修复了 node 8 错误。
