### ISSUE TITLE
Doesn't work behind proxy

### ISSUE THREAD

**Issue by cprn** [fannheyward/coc-marketplace#92]
Hi there.

I use marketplace at home okay but in the office all I get is this:

![image](https://user-images.githubusercontent.com/6132708/71182016-908e8a00-2275-11ea-82f6-09622ed1e970.png)

It never expands to the full list of extensions and searches don't work. The only difference is at work I have a proxy configured. I can get the same result at home when blocking `registry.npmjs.com` on the firewall.

Currently you're using `fetch`:
```ts
const resp = (await fetch(uri)) as any;
```

After quick search I'd propose to use `fetch-with-proxy` which seems to respect system settings and environment variables (example from the website, I don't code in TypeScript):
```ts
import fetch from 'fetch-with-proxy';
// ...
fetch(uri)
      .then((response) => response.text());
      .then(console.log)
      .catch(console.error)
```

**Comment by fannheyward** [comment]
How is your proxy configured? The `fetch` used is not https://github.com/github/fetch, but fetch model provided by coc.nvim https://github.com/neoclide/coc.nvim/blob/master/src/model/fetch.ts

**Comment by cprn** [comment]
This I didn't expect. I have the same proxy configuration in both Gnome and environment variables. It usually works fine when applications support system-wide proxy settings.

Gnome:

![image](https://user-images.githubusercontent.com/6132708/71262480-1ecf4280-2340-11ea-9282-2305655743f4.png)

`~/.bashrc`:
```
export http_proxy=http://proxiac:8080
export https_proxy=http://proxiac:8080
export ftp_proxy=http://proxiac:8080
export rsync_proxy=http://proxiac:8080
export all_proxy=http://proxiac:8080
export no_proxy="localhost,cy,127.0.0.1,127.0.0.1/8,::1,10.0.0.0/16,*.intra"

export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$https_proxy
export FTP_PROXY=$ftp_proxy
export RSYNC_PROXY=$rsync_proxy
export ALL_PROXY=$all_proxy
export NO_PROXY=$no_proxy
```

I also tried to replace our proxy hostname with IP but it didn't change anything. To make it even more interesting, `:CocInstall` works okay - my guess is it uses the same `fetch` implementation(?).

**Comment by fannheyward** [comment]
This has been fixed on coc.nvim mater https://github.com/neoclide/coc.nvim/commit/f4d9acae106a85b415449c7441174197623d29c0

**Comment by cprn** [comment]
The issue was never related to lower or upper case, I have all environment variables declared in both. I'll post it upstream, though.

**Comment by fannheyward** [comment]
Yes, both `:CocInstall ` and `coc-marketplace` are using same `fetch` model.

You can try to add `"http.proxy": "proxiac:8080"` to `coc-settings.json`.

**Comment by fannheyward** [comment]
Can you see `Using proxy from...` from `:CocOpenLog`?

**Comment by cprn** [comment]
I'm terribly sorry, it's a false alarm... a tricky one I would never expect, but still, not an issue in your code, I think. When I connect to http://registry.npmjs.com in the browser or with `curl` (through proxy) all works fine but when `coc.nvim::fetch` connects to that URL (through proxy) it gets `403 Forbidden`. It must be something set up by our admins but no idea why or what exactly - will investigate. If by any chance it is anything that should be fixed on your end (as in: a missing support for some rarely implemented nuance covered by the standard but I doubt it) I'll let you know.

For the completeness sake - yes, I see proxy in the log:
```
   11 2020-01-03T16:21:15.095 INFO (pid:29407) [model-fetch] - fetch: http://registry.npmjs.com/-/v1/search?text=keywords:coc.nvim&size=200&from=0
   12 2020-01-03T16:21:15.095 INFO (pid:29407) [model-fetch] - Using proxy from: proxiac:8080
```

And I can confirm it's taken from `coc-settings.json` (when set) or from environment variable.

P.s. Sorry for delay, winter holidays.

**Comment by cprn** [comment]
Few months passed and I still don't know why it doesn't work but I don't think it's something that concerns other users so I'm closing the issue. Have an awesome week, cheers!
