### ISSUE TITLE
Possible to install with plugin manager

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [fannheyward/coc-marketplace#93]
I'm trying to use [minpac](https://github.com/k-takata/minpac) to install coc.nvim extensions.

Right now I'm doing this . . . (Note that this a much shorter than the actual)
```vim
call minpac#add('neoclide/coc.nvim', {'branch': 'release'})
call minpac#add('fannheyward/coc-marketplace', {'do': 'silent !yarn install --frozen-lockfile'})
call minpac#add('neoclide/coc-git', {'do': 'silent !(yarn install --frozen-lockfile)'})
call minpac#add('neoclide/coc-tsserver', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
call minpac#add('neoclide/coc-html', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
call minpac#add('neoclide/coc-json', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
if executable('ra_lsp_server')
	call minpac#add('fannheyward/coc-rust-analyzer', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
elseif executable('rls')
	call minpac#add('neoclide/coc-rls', {'type': 'opt'}, {'do': 'silent !(yarn install --frozen-lockfile)'})
endif
```

I have installed the extensions as the [wik says here](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension) and minpac told me it's installed but I unable to run `:CocList marketplace`.

Running `:CocList extensions` it show me all off my extensions that should be loaded followed by [RTP], then version, then their path. coc-marketplace loads as enabled.

**Comment by fannheyward** [comment]
I'm not a `minipac` user, I just test this mini.vim

```
packadd minpac

call minpac#init()

" minpac must have {'type': 'opt'} so that it can be loaded with `packadd`.
call minpac#add('k-takata/minpac', {'type': 'opt'})

" Add other plugins here.
call minpac#add('neoclide/coc.nvim', {'branch': 'release'})
call minpac#add('fannheyward/coc-marketplace', {'do': 'silent !yarn install --frozen-lockfile'})

" Load the plugins right now. (optional)
" packloadall
```

and `nvim -u mini.vim`, then `call minpac#update()`, after installed, I can `:Cyclist marketplace`.

**Comment by fannheyward** [comment]
`:CocList extensions` shows:

`coc-marketplace [RTP] 1.5.0 ~/.config/nvim/pack/minpac/start/coc-marketplace`

**Comment by Th3Whit3Wolf** [comment]
I get the same result but when I run `:CocList marketplace` I get `[coc.nvim] List marketplace not found

**Comment by fannheyward** [comment]
I've fixed this issue on master. Please try again. It's dev-dependencies error.

**Comment by Th3Whit3Wolf** [comment]
Can confirm, thank you!
